name: cron_generator_annotations
description: A very easy way to generate crons, using a class to consolidate all your cron logic.
version: 0.0.2
repository: https://github.com/kmsbin/cron-generator

environment:
  sdk: ^3.3.0

dependencies:
  cron: ^0.6.0
  meta: ^1.12.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
