name: cron_generator_annotations
description: A very easy way to generate crons with dart or unix style.
version: 0.0.1
repository: https://github.com/kmsbin/cron-generator

environment:
  sdk: ^3.3.0

dependencies:
  cron: any
  meta: ^1.12.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
